---
title: "Dev.Book"
author: "Lamy Lionel, Kinart Adrien"
---

# Retrieve and format the sample 

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)

n = 30 
p = 0.5

sample = as.data.frame(read.csv("data/sample.csv"))
sample = sample %>% rename("ID" = X, "obs" = x) %>% arrange(obs)

distribution = table(sample %>% summarize(obs))/n

```
# Data description
## Comparing Densities

```{r}
x = seq(0, max(sample$obs), 1)
ggplot(mapping=aes(x)) +
  labs(title = "Estimated density vs Real density") +
  geom_col(aes(y=distribution), width = 0.05)  + 
  geom_point(aes(y=dgeom(x,p)), colour="blue", shape=1, size=2) +
  geom_line(aes(y=dgeom(x, p)), colour="blue") + 
  scale_y_continuous()

```

## Comparing Real CDF and Estimated CDF.

```{r}
ggplot(mapping=aes(x)) +
  labs(title="Empirical CDF vs Real CDF", y = "cum.probability") +
  geom_point(mapping = aes(y=pgeom(x,p)), colour="blue", shape=1, size=2) + 
  geom_line(mapping = aes(y=pgeom(x,p)), colour="blue") +
  stat_ecdf(geom="step", pad=F,mapping=aes(x=sample$obs))
```
## Disitrubtion
Faire l'équivalent de la figure 1.3. du sylla:
Pour la normal approximation, on pourrait faire pramatric ou non parametric..
```{r Figure 3 remake}
p_true <- c()
for (i in 1:1000) {
  Xtrue<-rgeom(n=30, prob=0.5 ) # true distribution
  cbind(p_true, (mean(Xtrue)+1)^(-1) )
}
#Xbar_n1_AN<- rnorm(n=10000000, mean = mu, sd= mu/sqrt(n1)) # AN approximation

p_bootstrap = NA
for (i in 1:1000) {
  Xstar <- sample(x=sample, size=30, replace=T)
  Tstar <- 1/30 * (sum(Xstar>=3))
  cbind(p_bootstrap, Tstar)
}

plot(density(p_true), col= 'blue', type="l", main="Densities", lty=1  , xlab="p" )
lines(density(p_bootstrap), col= 'green', type="l", lty=2)
legend("topright", legend=c("true", "Bootstrap"), col=c("blue", "green"), lty=1:2, cex=0.8)

```


# EStimator quality in the non parametric case 
## Bias and variance
### Assymptotically normal
#### Basic bootstrap

<!-- Not modified (except sample$obs) -->
```{r}
alpha = 0.05
B = 5000
M =1000



BB_vec_of_T <- rep(NA,M)
T_hat <- (1-(mean(sample$obs)+1)^(-1))^3
#T <- (1-(mu+1)^{-1} )^3
for (i in 1:B) {
  Xstar <- sample(sample$obs, replace = T) ; mu_star <- mean(Xstar)
  Tstar <- (1-(mu_star+1)^(-1))^3
  BB_vec_of_T[i] <- Tstar
}
CIboot <- c(quantile(BB_vec_of_T, 1-0.05/2), quantile(BB_vec_of_T, 0.05/2))

```


<!-- 
The cleanest option, imho, is to handle each task in a specific file (ie. "basic-bootstrap.R")
and to call it here by typing: source("path_to_file.R")
-->